parameters:
- name: location
  type: string
  default: 'centralindia'
- name: subscriptionId
  type: string
  default: '7831e4eb-265f-48c0-b2ca-f7370a400a35'
- name: environment
  type: string
  default: 'dev'
- name: conditiondeploybicep
  type: boolean
  default: true
- name: webAppName
  type: string
  default: 'Project-Alpha-India'
- name: appServiceName
  type: string
  default: 'dotnet-connectpluscpbackend'
- name: TemplateFolder
  type: string
  default: 'microsoft.sql/config'


stages:
# Stage for Validating template of Bicep
- stage: DeleteServices
  displayName: 'Delete Services'
  variables:
    _ResourceGroupName: '${{ parameters.webAppName }}-${{ upper(parameters.environment) }}'
    vmImageNameVaidate: 'windows-latest'
    vmImageName: 'windows-latest'
    resourceGroupName: ${{ parameters.webAppName }}-${{ upper(parameters.environment) }}
    environmentName: ${{ parameters.webAppName }}-${{ upper(parameters.environment) }}
  pool:
      vmImage: $(vmImageNameVaidate)
  jobs:
  - job: DeleteAppservice
    displayName: 'Delete App Service'
    steps:
      - task: AzureCLI@2
        enabled: true
        displayName: Delete command
        inputs:
          azureSubscription: ${{ variables['_ResourceGroupName'] }}
          scriptType: pscore
          workingDirectory: ${{ parameters.TemplateFolder }}
          scriptLocation: inlineScript
          inlineScript: |
            az webapp delete --verbose `
              --name 'dotnet-connectpluscpbackend' `
              --resource-group ${{ variables['ResourceGroupName'] }} `
              --debug

