# Azure Pipeline – Deploy Key Vault Secrets

parameters:
- name: azureServiceConnection
  type: string

- name: resourceGroupName
  type: string

- name: keyVaultName
  type: string


stages:

- stage: DeployKeyVaultSecrets
  displayName: Deploy Key Vault Secrets

  jobs:
  - job: DeploySecrets
    displayName: Deploy keyvault-secrets.bicep

    pool:
      vmImage: windows-latest

    steps:
######################################################################
    # Step 1 – Deploy secrets using Bicep template 
######################################################################
    - task: AzureCLI@2
      displayName: Deploy Secrets Bicep + DEV Blob Storage Secret
      inputs:
        azureSubscription: ${{ parameters.azureServiceConnection }}
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript: |

          Write-Host "Deploying Key Vault Secrets..."

          az deployment group create `
            --resource-group "${{ parameters.resourceGroupName }}" `
            --template-file "keyvault_config/keyvault-secrets.bicep" `
            --parameters keyVaultName="${{ parameters.keyVaultName }}" `
                        uatConnectionString="*" `
                        uatBlobConnectionString="*" `

          Write-Host "Key Vault Secrets deployment completed."

######################################################################
    # Step 2 – Delete incorrect secrets
######################################################################
      # - task: AzureCLI@2
      #   displayName: Delete incorrect UAT & PROD secrets
      #   inputs:
      #     azureSubscription: ${{ parameters.azureServiceConnection }}
      #     scriptType: pscore
      #     scriptLocation: inlineScript
      #     inlineScript: |

      #       Write-Host "Deleting incorrect secrets from DEV Key Vault..."

      #       az keyvault secret delete `
      #         --vault-name "${{ parameters.keyVaultName }}" `
      #         --name "ConnectionStrings--UAT"

      #       az keyvault secret delete `
      #         --vault-name "${{ parameters.keyVaultName }}" `
      #         --name "ConnectionStrings--Prod"

      #       Write-Host "Incorrect secrets deleted."
